//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusProductAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NEXUSPRODUCTEntities : DbContext
    {
        public NEXUSPRODUCTEntities()
            : base("name=NEXUSPRODUCTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<VSR_Mst_OwnVehicles_GetAll_Result> VSR_Mst_OwnVehicles_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Mst_OwnVehicles_GetAll_Result>("VSR_Mst_OwnVehicles_GetAll");
        }
    
        public virtual int VSR_Mst_ServiceTypes_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VSR_Mst_ServiceTypes_Delete", iDParameter);
        }
    
        public virtual ObjectResult<VSR_Mst_ServiceTypes_GetAll_Result> VSR_Mst_ServiceTypes_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Mst_ServiceTypes_GetAll_Result>("VSR_Mst_ServiceTypes_GetAll");
        }
    
        public virtual int VSR_Mst_ServiceTypes_Save(string serviceTypeNameEn, string serviceTypeNameAr, string descriptionEn, Nullable<int> iD)
        {
            var serviceTypeNameEnParameter = serviceTypeNameEn != null ?
                new ObjectParameter("ServiceTypeNameEn", serviceTypeNameEn) :
                new ObjectParameter("ServiceTypeNameEn", typeof(string));
    
            var serviceTypeNameArParameter = serviceTypeNameAr != null ?
                new ObjectParameter("serviceTypeNameAr", serviceTypeNameAr) :
                new ObjectParameter("serviceTypeNameAr", typeof(string));
    
            var descriptionEnParameter = descriptionEn != null ?
                new ObjectParameter("DescriptionEn", descriptionEn) :
                new ObjectParameter("DescriptionEn", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VSR_Mst_ServiceTypes_Save", serviceTypeNameEnParameter, serviceTypeNameArParameter, descriptionEnParameter, iDParameter);
        }
    
        public virtual int VSR_Mst_VehicleTypes_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VSR_Mst_VehicleTypes_Delete", iDParameter);
        }
    
        public virtual ObjectResult<VSR_Mst_VehicleTypes_GetAll_Result> VSR_Mst_VehicleTypes_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Mst_VehicleTypes_GetAll_Result>("VSR_Mst_VehicleTypes_GetAll");
        }
    
        public virtual int VSR_Mst_VehicleTypes_Save(string vehicleTypeNameEn, string descriptionEn, Nullable<int> iD)
        {
            var vehicleTypeNameEnParameter = vehicleTypeNameEn != null ?
                new ObjectParameter("VehicleTypeNameEn", vehicleTypeNameEn) :
                new ObjectParameter("VehicleTypeNameEn", typeof(string));
    
            var descriptionEnParameter = descriptionEn != null ?
                new ObjectParameter("DescriptionEn", descriptionEn) :
                new ObjectParameter("DescriptionEn", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VSR_Mst_VehicleTypes_Save", vehicleTypeNameEnParameter, descriptionEnParameter, iDParameter);
        }
    
        public virtual int VSR_STN_OpeningCount_Save(Nullable<int> actualCount)
        {
            var actualCountParameter = actualCount.HasValue ?
                new ObjectParameter("actualCount", actualCount) :
                new ObjectParameter("actualCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VSR_STN_OpeningCount_Save", actualCountParameter);
        }
    
        public virtual ObjectResult<VSR_STN_ServicePricing_GetAllByServiceID_Result> VSR_STN_ServicePricing_GetAllByServiceID(Nullable<int> serviceID)
        {
            var serviceIDParameter = serviceID.HasValue ?
                new ObjectParameter("ServiceID", serviceID) :
                new ObjectParameter("ServiceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_STN_ServicePricing_GetAllByServiceID_Result>("VSR_STN_ServicePricing_GetAllByServiceID", serviceIDParameter);
        }
    
        public virtual ObjectResult<VSR_STN_ServicePricing_GetAllByVehicleTypeID_Result> VSR_STN_ServicePricing_GetAllByVehicleTypeID(Nullable<int> vehicleTypeId)
        {
            var vehicleTypeIdParameter = vehicleTypeId.HasValue ?
                new ObjectParameter("vehicleTypeId", vehicleTypeId) :
                new ObjectParameter("vehicleTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_STN_ServicePricing_GetAllByVehicleTypeID_Result>("VSR_STN_ServicePricing_GetAllByVehicleTypeID", vehicleTypeIdParameter);
        }
    
        public virtual ObjectResult<VSR_STN_ServicePricing_GetAllByVehicleTypeIDAndBayType_Result> VSR_STN_ServicePricing_GetAllByVehicleTypeIDAndBayType(Nullable<int> vehicleTypeId, Nullable<int> bayType)
        {
            var vehicleTypeIdParameter = vehicleTypeId.HasValue ?
                new ObjectParameter("vehicleTypeId", vehicleTypeId) :
                new ObjectParameter("vehicleTypeId", typeof(int));
    
            var bayTypeParameter = bayType.HasValue ?
                new ObjectParameter("BayType", bayType) :
                new ObjectParameter("BayType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_STN_ServicePricing_GetAllByVehicleTypeIDAndBayType_Result>("VSR_STN_ServicePricing_GetAllByVehicleTypeIDAndBayType", vehicleTypeIdParameter, bayTypeParameter);
        }
    
        public virtual int VSR_STN_ServicePricing_Save(Nullable<int> serviceTypeID, string pricing)
        {
            var serviceTypeIDParameter = serviceTypeID.HasValue ?
                new ObjectParameter("ServiceTypeID", serviceTypeID) :
                new ObjectParameter("ServiceTypeID", typeof(int));
    
            var pricingParameter = pricing != null ?
                new ObjectParameter("Pricing", pricing) :
                new ObjectParameter("Pricing", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VSR_STN_ServicePricing_Save", serviceTypeIDParameter, pricingParameter);
        }
    
        public virtual ObjectResult<VSR_Trn_ServiceEntry_Details_GetAllByEntryId_Result> VSR_Trn_ServiceEntry_Details_GetAllByEntryId(Nullable<int> entryId)
        {
            var entryIdParameter = entryId.HasValue ?
                new ObjectParameter("EntryId", entryId) :
                new ObjectParameter("EntryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Trn_ServiceEntry_Details_GetAllByEntryId_Result>("VSR_Trn_ServiceEntry_Details_GetAllByEntryId", entryIdParameter);
        }
    
        public virtual ObjectResult<VSR_Trn_ServiceEntry_GetAll_Result> VSR_Trn_ServiceEntry_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Trn_ServiceEntry_GetAll_Result>("VSR_Trn_ServiceEntry_GetAll");
        }
    
        public virtual ObjectResult<VSR_Trn_ServiceEntry_GetDashboardData_Result> VSR_Trn_ServiceEntry_GetDashboardData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Trn_ServiceEntry_GetDashboardData_Result>("VSR_Trn_ServiceEntry_GetDashboardData");
        }
    
        public virtual ObjectResult<Nullable<int>> VSR_Trn_ServiceEntry_IsShowOpening()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VSR_Trn_ServiceEntry_IsShowOpening");
        }
    
        public virtual ObjectResult<Nullable<int>> VSR_Trn_ServiceEntry_Save(Nullable<int> entryStartNo, Nullable<int> bayType, Nullable<int> partyType, string vehicleNumber, Nullable<int> vehicleType, string imgUrl, string remarks, string customerName, Nullable<decimal> totalAmount, Nullable<decimal> discount, Nullable<decimal> netAmount, string details)
        {
            var entryStartNoParameter = entryStartNo.HasValue ?
                new ObjectParameter("EntryStartNo", entryStartNo) :
                new ObjectParameter("EntryStartNo", typeof(int));
    
            var bayTypeParameter = bayType.HasValue ?
                new ObjectParameter("BayType", bayType) :
                new ObjectParameter("BayType", typeof(int));
    
            var partyTypeParameter = partyType.HasValue ?
                new ObjectParameter("PartyType", partyType) :
                new ObjectParameter("PartyType", typeof(int));
    
            var vehicleNumberParameter = vehicleNumber != null ?
                new ObjectParameter("VehicleNumber", vehicleNumber) :
                new ObjectParameter("VehicleNumber", typeof(string));
    
            var vehicleTypeParameter = vehicleType.HasValue ?
                new ObjectParameter("VehicleType", vehicleType) :
                new ObjectParameter("VehicleType", typeof(int));
    
            var imgUrlParameter = imgUrl != null ?
                new ObjectParameter("ImgUrl", imgUrl) :
                new ObjectParameter("ImgUrl", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var totalAmountParameter = totalAmount.HasValue ?
                new ObjectParameter("TotalAmount", totalAmount) :
                new ObjectParameter("TotalAmount", typeof(decimal));
    
            var discountParameter = discount.HasValue ?
                new ObjectParameter("Discount", discount) :
                new ObjectParameter("Discount", typeof(decimal));
    
            var netAmountParameter = netAmount.HasValue ?
                new ObjectParameter("NetAmount", netAmount) :
                new ObjectParameter("NetAmount", typeof(decimal));
    
            var detailsParameter = details != null ?
                new ObjectParameter("details", details) :
                new ObjectParameter("details", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VSR_Trn_ServiceEntry_Save", entryStartNoParameter, bayTypeParameter, partyTypeParameter, vehicleNumberParameter, vehicleTypeParameter, imgUrlParameter, remarksParameter, customerNameParameter, totalAmountParameter, discountParameter, netAmountParameter, detailsParameter);
        }
    
        public virtual ObjectResult<VSR_Trn_ServiceEntry_Head_getMaxEntryNo_Result> VSR_Trn_ServiceEntry_Head_getMaxEntryNo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Trn_ServiceEntry_Head_getMaxEntryNo_Result>("VSR_Trn_ServiceEntry_Head_getMaxEntryNo");
        }
    
        public virtual int HRP_Mst_BloodGroups_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_BloodGroups_Delete", iDParameter);
        }
    
        public virtual int HRP_Mst_BloodGroups_Save(string bGCode, string bGCodeName, Nullable<int> iD)
        {
            var bGCodeParameter = bGCode != null ?
                new ObjectParameter("BGCode", bGCode) :
                new ObjectParameter("BGCode", typeof(string));
    
            var bGCodeNameParameter = bGCodeName != null ?
                new ObjectParameter("BGCodeName", bGCodeName) :
                new ObjectParameter("BGCodeName", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_BloodGroups_Save", bGCodeParameter, bGCodeNameParameter, iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_BloodGroups_GetAll_Result> HRP_Mst_BloodGroups_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_BloodGroups_GetAll_Result>("HRP_Mst_BloodGroups_GetAll");
        }
    
        public virtual int HRP_Mst_Country_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Country_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_Country_GetAll_Result> HRP_Mst_Country_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_Country_GetAll_Result>("HRP_Mst_Country_GetAll");
        }
    
        public virtual int HRP_Mst_Country_Save(string countryCode, string countryName, Nullable<int> iD)
        {
            var countryCodeParameter = countryCode != null ?
                new ObjectParameter("CountryCode", countryCode) :
                new ObjectParameter("CountryCode", typeof(string));
    
            var countryNameParameter = countryName != null ?
                new ObjectParameter("CountryName", countryName) :
                new ObjectParameter("CountryName", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Country_Save", countryCodeParameter, countryNameParameter, iDParameter);
        }
    
        public virtual int HRP_Mst_Designation_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Designation_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_Designation_GetAll_Result> HRP_Mst_Designation_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_Designation_GetAll_Result>("HRP_Mst_Designation_GetAll");
        }
    
        public virtual int HRP_Mst_Designation_Save(string designationCode, string designationName, Nullable<int> iD)
        {
            var designationCodeParameter = designationCode != null ?
                new ObjectParameter("DesignationCode", designationCode) :
                new ObjectParameter("DesignationCode", typeof(string));
    
            var designationNameParameter = designationName != null ?
                new ObjectParameter("DesignationName", designationName) :
                new ObjectParameter("DesignationName", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Designation_Save", designationCodeParameter, designationNameParameter, iDParameter);
        }
    
        public virtual int HRP_Mst_Departments_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Departments_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_Departments_GetAll_Result> HRP_Mst_Departments_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_Departments_GetAll_Result>("HRP_Mst_Departments_GetAll");
        }
    
        public virtual int HRP_Mst_Departments_Save(string deptCode, string deptName, Nullable<int> iD)
        {
            var deptCodeParameter = deptCode != null ?
                new ObjectParameter("DeptCode", deptCode) :
                new ObjectParameter("DeptCode", typeof(string));
    
            var deptNameParameter = deptName != null ?
                new ObjectParameter("DeptName", deptName) :
                new ObjectParameter("DeptName", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Departments_Save", deptCodeParameter, deptNameParameter, iDParameter);
        }
    
        public virtual int HRP_Mst_Bank_Save(string bankCode, string bankName, Nullable<int> iD)
        {
            var bankCodeParameter = bankCode != null ?
                new ObjectParameter("bankCode", bankCode) :
                new ObjectParameter("bankCode", typeof(string));
    
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Bank_Save", bankCodeParameter, bankNameParameter, iDParameter);
        }
    
        public virtual int HRP_Mst_EmpDocs_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_EmpDocs_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_EmpDocs_GetAll_Result> HRP_Mst_EmpDocs_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_EmpDocs_GetAll_Result>("HRP_Mst_EmpDocs_GetAll");
        }
    
        public virtual int HRP_Mst_EmpDocs_Save(string empdocCode, string empdocName, Nullable<int> iD)
        {
            var empdocCodeParameter = empdocCode != null ?
                new ObjectParameter("empdocCode", empdocCode) :
                new ObjectParameter("empdocCode", typeof(string));
    
            var empdocNameParameter = empdocName != null ?
                new ObjectParameter("empdocName", empdocName) :
                new ObjectParameter("empdocName", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_EmpDocs_Save", empdocCodeParameter, empdocNameParameter, iDParameter);
        }
    
        public virtual int HRP_Mst_Subcontractors_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Subcontractors_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_Subcontractors_GetAll_Result> HRP_Mst_Subcontractors_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_Subcontractors_GetAll_Result>("HRP_Mst_Subcontractors_GetAll");
        }
    
        public virtual int HRP_Mst_Subcontractors_Save(string subcontractorCode, string subcontractorName, string contactPerson, string contactNumber, string contactEmail, Nullable<int> iD)
        {
            var subcontractorCodeParameter = subcontractorCode != null ?
                new ObjectParameter("subcontractorCode", subcontractorCode) :
                new ObjectParameter("subcontractorCode", typeof(string));
    
            var subcontractorNameParameter = subcontractorName != null ?
                new ObjectParameter("subcontractorName", subcontractorName) :
                new ObjectParameter("subcontractorName", typeof(string));
    
            var contactPersonParameter = contactPerson != null ?
                new ObjectParameter("ContactPerson", contactPerson) :
                new ObjectParameter("ContactPerson", typeof(string));
    
            var contactNumberParameter = contactNumber != null ?
                new ObjectParameter("ContactNumber", contactNumber) :
                new ObjectParameter("ContactNumber", typeof(string));
    
            var contactEmailParameter = contactEmail != null ?
                new ObjectParameter("ContactEmail", contactEmail) :
                new ObjectParameter("ContactEmail", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Subcontractors_Save", subcontractorCodeParameter, subcontractorNameParameter, contactPersonParameter, contactNumberParameter, contactEmailParameter, iDParameter);
        }
    
        public virtual int HRP_Mst_WorkLocation_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_WorkLocation_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_WorkLocation_GetAll_Result> HRP_Mst_WorkLocation_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_WorkLocation_GetAll_Result>("HRP_Mst_WorkLocation_GetAll");
        }
    
        public virtual int HRP_Mst_WorkLocation_Save(string workLocationCode, string workLocationName, string contactPerson, string contactNumber, string contactEmail, Nullable<int> iD)
        {
            var workLocationCodeParameter = workLocationCode != null ?
                new ObjectParameter("WorkLocationCode", workLocationCode) :
                new ObjectParameter("WorkLocationCode", typeof(string));
    
            var workLocationNameParameter = workLocationName != null ?
                new ObjectParameter("WorkLocationName", workLocationName) :
                new ObjectParameter("WorkLocationName", typeof(string));
    
            var contactPersonParameter = contactPerson != null ?
                new ObjectParameter("ContactPerson", contactPerson) :
                new ObjectParameter("ContactPerson", typeof(string));
    
            var contactNumberParameter = contactNumber != null ?
                new ObjectParameter("ContactNumber", contactNumber) :
                new ObjectParameter("ContactNumber", typeof(string));
    
            var contactEmailParameter = contactEmail != null ?
                new ObjectParameter("ContactEmail", contactEmail) :
                new ObjectParameter("ContactEmail", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_WorkLocation_Save", workLocationCodeParameter, workLocationNameParameter, contactPersonParameter, contactNumberParameter, contactEmailParameter, iDParameter);
        }
    
        public virtual int HRP_Mst_Bank_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Bank_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_Bank_GetAll_Result> HRP_Mst_Bank_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_Bank_GetAll_Result>("HRP_Mst_Bank_GetAll");
        }
    
        public virtual ObjectResult<VSR_Trn_ServiceEntryDetails_GetByServeEntryID_Result> VSR_Trn_ServiceEntryDetails_GetByServeEntryID(Nullable<int> serviceEntryID)
        {
            var serviceEntryIDParameter = serviceEntryID.HasValue ?
                new ObjectParameter("ServiceEntryID", serviceEntryID) :
                new ObjectParameter("ServiceEntryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VSR_Trn_ServiceEntryDetails_GetByServeEntryID_Result>("VSR_Trn_ServiceEntryDetails_GetByServeEntryID", serviceEntryIDParameter);
        }
    
        public virtual int HRP_Mst_Employee_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_Employee_Delete", iDParameter);
        }
    
        public virtual int HRP_Mst_EmployeeDocuments_Delete(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_EmployeeDocuments_Delete", iDParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_EmployeeDocuments_GetAll_Result> HRP_Mst_EmployeeDocuments_GetAll(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_EmployeeDocuments_GetAll_Result>("HRP_Mst_EmployeeDocuments_GetAll", iDParameter);
        }
    
        public virtual int HRP_Mst_EmployeeDocuments_Save(Nullable<int> empId, string details)
        {
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            var detailsParameter = details != null ?
                new ObjectParameter("details", details) :
                new ObjectParameter("details", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HRP_Mst_EmployeeDocuments_Save", empIdParameter, detailsParameter);
        }
    
        public virtual ObjectResult<HRP_Mst_Employee_GetAll_Result> HRP_Mst_Employee_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HRP_Mst_Employee_GetAll_Result>("HRP_Mst_Employee_GetAll");
        }
    
        public virtual ObjectResult<Nullable<int>> HRP_Mst_Employee_Save(string empID, string empName, string gender, Nullable<int> nationality, string primaryIDNo, Nullable<System.DateTime> dOB, string phone, string email, Nullable<System.DateTime> dOJ, Nullable<int> designation, Nullable<int> department, Nullable<int> workLocation, string empType, Nullable<int> subcontractorId, string timing, Nullable<int> reportingTo, Nullable<int> bank, string branch, string swiftCode, string accNo, Nullable<int> bloodgroup, Nullable<int> iD)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(string));
    
            var empNameParameter = empName != null ?
                new ObjectParameter("EmpName", empName) :
                new ObjectParameter("EmpName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var nationalityParameter = nationality.HasValue ?
                new ObjectParameter("Nationality", nationality) :
                new ObjectParameter("Nationality", typeof(int));
    
            var primaryIDNoParameter = primaryIDNo != null ?
                new ObjectParameter("PrimaryIDNo", primaryIDNo) :
                new ObjectParameter("PrimaryIDNo", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var dOJParameter = dOJ.HasValue ?
                new ObjectParameter("DOJ", dOJ) :
                new ObjectParameter("DOJ", typeof(System.DateTime));
    
            var designationParameter = designation.HasValue ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(int));
    
            var departmentParameter = department.HasValue ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(int));
    
            var workLocationParameter = workLocation.HasValue ?
                new ObjectParameter("WorkLocation", workLocation) :
                new ObjectParameter("WorkLocation", typeof(int));
    
            var empTypeParameter = empType != null ?
                new ObjectParameter("EmpType", empType) :
                new ObjectParameter("EmpType", typeof(string));
    
            var subcontractorIdParameter = subcontractorId.HasValue ?
                new ObjectParameter("SubcontractorId", subcontractorId) :
                new ObjectParameter("SubcontractorId", typeof(int));
    
            var timingParameter = timing != null ?
                new ObjectParameter("Timing", timing) :
                new ObjectParameter("Timing", typeof(string));
    
            var reportingToParameter = reportingTo.HasValue ?
                new ObjectParameter("ReportingTo", reportingTo) :
                new ObjectParameter("ReportingTo", typeof(int));
    
            var bankParameter = bank.HasValue ?
                new ObjectParameter("Bank", bank) :
                new ObjectParameter("Bank", typeof(int));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var swiftCodeParameter = swiftCode != null ?
                new ObjectParameter("SwiftCode", swiftCode) :
                new ObjectParameter("SwiftCode", typeof(string));
    
            var accNoParameter = accNo != null ?
                new ObjectParameter("AccNo", accNo) :
                new ObjectParameter("AccNo", typeof(string));
    
            var bloodgroupParameter = bloodgroup.HasValue ?
                new ObjectParameter("bloodgroup", bloodgroup) :
                new ObjectParameter("bloodgroup", typeof(int));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("HRP_Mst_Employee_Save", empIDParameter, empNameParameter, genderParameter, nationalityParameter, primaryIDNoParameter, dOBParameter, phoneParameter, emailParameter, dOJParameter, designationParameter, departmentParameter, workLocationParameter, empTypeParameter, subcontractorIdParameter, timingParameter, reportingToParameter, bankParameter, branchParameter, swiftCodeParameter, accNoParameter, bloodgroupParameter, iDParameter);
        }
    
        public virtual ObjectResult<CMN_Mst_UserRoles_GetAll_Result> CMN_Mst_UserRoles_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Mst_UserRoles_GetAll_Result>("CMN_Mst_UserRoles_GetAll");
        }
    
        public virtual int CMN_Mst_UserRoles_Save(string userRoleNameEn)
        {
            var userRoleNameEnParameter = userRoleNameEn != null ?
                new ObjectParameter("UserRoleNameEn", userRoleNameEn) :
                new ObjectParameter("UserRoleNameEn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CMN_Mst_UserRoles_Save", userRoleNameEnParameter);
        }
    
        public virtual ObjectResult<CMN_Utl_Modules_GetAll_Result> CMN_Utl_Modules_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Utl_Modules_GetAll_Result>("CMN_Utl_Modules_GetAll");
        }
    
        public virtual int CMN_STN_RoleToMenu_Save(Nullable<int> roleId, string details)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            var detailsParameter = details != null ?
                new ObjectParameter("details", details) :
                new ObjectParameter("details", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CMN_STN_RoleToMenu_Save", roleIdParameter, detailsParameter);
        }
    
        public virtual ObjectResult<CMN_STN_RoleToMenu_GetAll_Result> CMN_STN_RoleToMenu_GetAll(Nullable<int> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_STN_RoleToMenu_GetAll_Result>("CMN_STN_RoleToMenu_GetAll", roleIdParameter);
        }
    
        public virtual ObjectResult<CMN_Utl_Menu_GetAll_Result> CMN_Utl_Menu_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Utl_Menu_GetAll_Result>("CMN_Utl_Menu_GetAll");
        }
    
        public virtual ObjectResult<CMN_Utl_MenuItems_GetAll_Result> CMN_Utl_MenuItems_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Utl_MenuItems_GetAll_Result>("CMN_Utl_MenuItems_GetAll");
        }
    
        public virtual ObjectResult<CMN_Utl_Menu_GetAll_ByRoleID_Result> CMN_Utl_Menu_GetAll_ByRoleID(Nullable<int> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Utl_Menu_GetAll_ByRoleID_Result>("CMN_Utl_Menu_GetAll_ByRoleID", roleIdParameter);
        }
    
        public virtual ObjectResult<CMN_Utl_MenuItems_GetAll_ByRoleID_Result> CMN_Utl_MenuItems_GetAll_ByRoleID(Nullable<int> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Utl_MenuItems_GetAll_ByRoleID_Result>("CMN_Utl_MenuItems_GetAll_ByRoleID", roleIdParameter);
        }
    
        public virtual ObjectResult<CMN_Utl_Modules_GetAll_ByRoleID_Result> CMN_Utl_Modules_GetAll_ByRoleID(Nullable<int> roleId)
        {
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Utl_Modules_GetAll_ByRoleID_Result>("CMN_Utl_Modules_GetAll_ByRoleID", roleIdParameter);
        }
    
        public virtual ObjectResult<CMN_Mst_User_Authenticate_Result> CMN_Mst_User_Authenticate(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CMN_Mst_User_Authenticate_Result>("CMN_Mst_User_Authenticate", userNameParameter, passwordParameter);
        }
    }
}
